apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: default
  namespace: app-of-apps
spec:
  destination:
    namespace: app-of-apps
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: app-of-apps
    targetRevision: main
    repoURL: https://github.com/YoussefMobarak1702/app1

